source 'https://rubygems.org'
# ruby `cat .ruby-version`.to_s
gem 'bundler', '>= 2.0.1'
gem 'cucumber', '~> 3.1.0'
# gem 'faker'
# gem 'pry'
# gem 'pry-remote'
# gem 'pry-nav'
# gem 'rspec', '~> 3.7.0'
gem 'selenium-webdriver'
gem 'rake'
# gem 'site_prism', '~> 3.0'
